# Generated by Django 2.2.1 on 2019-05-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img1',
            field=models.FileField(default=2, upload_to='item/'),
            preserve_default=False,
        ),
    ]
