# Generated by Django 2.2.1 on 2019-05-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190519_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('NOR', 'Normal'), ('NEW', 'New'), ('SOL', 'Solde')], default='NOR', max_length=1),
        ),
    ]
